# Generated by Django 5.0 on 2023-12-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imobiliaria/'),
        ),
    ]
