# Generated by Django 5.0 on 2023-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imobiliaria_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='token_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
