# Generated by Django 5.0 on 2023-12-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_imobiliaria_token_imobiliaria_token_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('residencial', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Comercial', 'Comercial'), ('Sala Comercial', 'Sala Comercial')], max_length=50)),
                ('metros_quadrados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quartos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('banheiros', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vagas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aluguel', models.BooleanField(default=False)),
                ('temporada', models.BooleanField(default=False)),
                ('imobiliaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.imobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='FotosImoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
        ),
    ]
