# Generated by Django 5.0 on 2023-12-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FotosImoveis',
            new_name='FotosImovel',
        ),
    ]
