# Generated by Django 5.0 on 2023-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_rename_fotosimoveis_fotosimovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
